# setting the menu
menu: 
  - name: Home
    link: /
  - name: Projects
    link: /projects
  - name: Publications
    link: /publications
  - name: Archive
    link: /archive
  - name: Search
    link: /search
  - name: Team
    link: /team

    
#  - name: Follow me
#    submenu:
#      - name: GitHub
#        icon: github
#        link: http://github.com/alainpham
#      - name: LinkedIn
#        icon: linkedin-square
#        link: http://www.linkedin.com/in/alainpham

#  - name: Categories
#    link: /categories
#  - name: Tags
#    link: /tags
#  - name: About
#    link: /about


